### ISSUE TITLE
키워드 검색 시 검색 내용 표시

### ISSUE THREAD

**Issue by YubinMoon** [likelion-backend-6th/studyon#167]
키워드를 검색했을 때 url query에는 검색 단어가 표시되지만 키워드 검색창에 표시되지 않는 문제

![image](https://github.com/likelion-backend-6th/studyon/assets/66174567/17b0c2c1-1331-44f5-9d43-2a9b2cbbc9b5)

**Comment by 25th-Night** [comment]
게시판 페이지에도 이거 수정해야 겠네요 이런..ㅋㅋ

**Comment by YubinMoon** [comment]
제가 작업 하겠습니다
