### ISSUE TITLE
스타일 관련 확인 요청사항

### ISSUE THREAD

**Issue by 25th-Night** [likelion-backend-6th/studyon#214]
전체
- border-radius를 통일하는게 좋을 거 같습니다. 페이지별로 border-radius 적용이 다 다르게 되어 있는거 같습니다.
  - 메인페이지, 로그인, 회원가입

스터디 관리 세부 페이지
- 진행방식, 추가정보 란이 좌측으로 정렬되는게 보기에 좋을 것 같습니다.
![image](https://github.com/likelion-backend-6th/studyon/assets/104040502/12c0ef9f-d2fd-4b7b-80b8-702c3f940319)

**Comment by YubinMoon** [comment]
border-radius를 최대한 쓰지 않는 방향으로 변경되었습니다
