### ISSUE TITLE
스터디 모집 생성 - 태그 선택 JS 동작 에러

### ISSUE THREAD

**Issue by 25th-Night** [likelion-backend-6th/studyon#216]
스터디 모집 생성 페이지에서 아래의 경우에 태그를 클릭해도 반응이 없습니다.

- 데이터 입력 -> 등록 버튼 클릭 -> 유효성을 통과하지 못해 해당 페이지로 다시 돌아온 상황

해당 부분 확인이 필요할 듯 합니다.

**Comment by YubinMoon** [comment]
확인했습니다. document가 생성될 때 JS가 실행되게끔 하면 해결될 듯 하네요
webRTC쪽 마무리 하고 고치겠습니다.
