### ISSUE TITLE
스터디 관리 메인 페이지

### ISSUE THREAD

**Issue by 98Taek** [likelion-backend-6th/studyon#325]
<img width="221" alt="스크린샷 2023-10-19 오전 9 49 12" src="https://github.com/likelion-backend-6th/studyon/assets/134459651/cd94641f-b9fe-4e81-b673-173348448f46">

화면이 줄어들면 Leave버튼이 사라지는 문제

<img width="275" alt="스크린샷 2023-10-19 오전 9 47 45" src="https://github.com/likelion-backend-6th/studyon/assets/134459651/6136dd96-1b51-4a59-93af-a43b6181b6cb">

화면이 줄어들면 Delete버튼이 사라지는 문제(많이 줄이면 글자도 겹치긴 합니다.)

**Comment by 25th-Night** [comment]
#330 에서 해결 완료
