### ISSUE TITLE
모집글 생성 페이지 - 태그선택

### ISSUE THREAD

**Issue by 98Taek** [likelion-backend-6th/studyon#333]
태그 선택을 안해고 작성완료 버튼을 누르면 에러메시지가 나오지않는 문제

**Comment by YubinMoon** [comment]
이부분이 원래 아래 사진처럼 textfield에 자동으로 메시지가 나타나야는데 input이 hidden처리되어있어서 에러 팝업도 같이 안나오는 것 같네요

![image](https://github.com/likelion-backend-6th/studyon/assets/66174567/c5c8ae97-aa91-419e-bb03-7ad23a886f83)
